DELETE http://localhost:8080/events/4/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdvcmtlbUBleGFtcGxlLmNvc20iLCJleHAiOjE3NDU2NjczMDksInVzZXJJZCI6Mn0.RFuB0Jp5vFGZOVxZvFp4lpyftc5doinCqm8tfHCYoOY