PUT http://localhost:8080/users/12/password
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZpcnN0YWRtaW5AZXhhbXBsZS5jb20iLCJleHAiOjE3NDYxMzkwNDYsInJvbGUiOiJhZG1pbiIsInVzZXJJZCI6MTJ9.j9rlUkVz1Tj4l_UJIfPluaz_kUMl9S_fEelAskxT4p8

{
    "password":"firstadmin",
    "newPassword":"alala"
}