DELETE http://localhost:8080/events/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9udXJAZXhhbXBsZS5jb3NtIiwiZXhwIjoxNzQ1NTg4MjAxLCJ1c2VySWQiOjF9.MuL1eKw6QeHd3HQp9qOu_3mPsTV-OMFNobtV33m20hs