DELETE http://localhost:8080/events/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdvcmtlbUBleGFtcGxlLmNvc20iLCJleHAiOjE3NDU3NzE5MDgsInJvbGUiOiJ1c2VyIiwidXNlcklkIjoxfQ.mAHIqAuod2n1I3jPbw3ZlVcHvqjZ8lTjq4CWFBqMnQ4