DELETE http://localhost:8080/events/28
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdvcmtlbXV5c2FTQGV4YW1wbGUuY29zbSIsImV4cCI6MTc0NTU4NDU4MSwidXNlcklkIjoxMX0.Xx-Fmii8qnBSgo-TMxkJCYgjz6WhYgjWIJsIuPHtlQg