DELETE http://localhost:8080/users/3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQ2MTIxMjczLCJyb2xlIjoiYWRtaW4iLCJ1c2VySWQiOjZ9.q7zE_hKtSw6Lnrhp-POCElcLALlkZKGu592MpYxxiXM