GET http://localhost:8080/admin/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQ2MTE5MTMxLCJyb2xlIjoiYWRtaW4iLCJ1c2VySWQiOjZ9.9bcXZPqg_SM7sUONG7AptU_ee7EEMpbEYySTYx_n2TQ