GET http://localhost:8080/admin/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluMUBleGFtcGxlLmNvbSIsImV4cCI6MTc0NjExNDUyMiwicm9sZSI6ImFkbWluIiwidXNlcklkIjo0fQ.weEzdGND22nwuuCZOp3MvSYnjGclnSPwPGHmb4wWeXU