POST http://localhost:8080/events/5/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIyZW1haWxAZXhhbXBsZS5jb20iLCJleHAiOjE3NDU5NTg2NDEsInJvbGUiOiJhZG1pbiIsInVzZXJJZCI6Mn0.kC7o-Zn_DvCNzsVRRxddJe388Br7W1RbNXSp6bXl-jo